"""Add Patient and Study models

Revision ID: c807c4a029cf
Revises: 
Create Date: 2026-05-23 11:09:52.300341+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c807c4a029cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('study_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_study_id'), 'jobs', ['study_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_study_id'), table_name='jobs')
    op.drop_column('jobs', 'study_id')
    # ### end Alembic commands ###
