"""
Lumenis AI — Report Schemas

Pydantic models for citations, structured report findings,
and the complete clinical report response.
"""

from __future__ import annotations

import uuid

from pydantic import BaseModel, Field

from app.schemas.findings import Finding


class Citation(BaseModel):
    """Reference to a medical-literature source or knowledge-base entry."""

    source_id: str = Field(
        ...,
        description="Unique identifier for the source document or article",
        examples=["PMC12345678", "doi:10.1000/xyz123"],
    )
    source_text: str = Field(
        ...,
        description="Relevant excerpt or title from the source",
    )
    relevance_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Semantic relevance of this citation to the finding (0–1)",
    )


class ReportFinding(BaseModel):
    """A single finding enriched with explanation, citations, and verification."""

    finding: Finding = Field(
        ...,
        description="The core clinical finding",
    )
    explanation: str = Field(
        ...,
        description="Detailed clinical explanation contextualising the finding",
    )
    citations: list[Citation] = Field(
        default_factory=list,
        description="Supporting literature citations",
    )
    verified: bool = Field(
        default=False,
        description="Whether this finding has been cross-verified against the knowledge base",
    )


_DISCLAIMER = (
    "This report is generated by an AI system and is intended for informational "
    "purposes only. It does NOT constitute a medical diagnosis. Always consult a "
    "qualified healthcare professional for clinical decisions."
)


class FullReport(BaseModel):
    """Complete clinical report returned to the client."""

    job_id: uuid.UUID = Field(
        ...,
        description="ID of the originating analysis job",
    )
    summary: str = Field(
        ...,
        description="Narrative summary of all findings and impressions",
    )
    findings: list[ReportFinding] = Field(
        default_factory=list,
        description="Structured findings with explanations and citations",
    )
    severity_overall: str = Field(
        ...,
        description="Aggregate severity (low / moderate / high / critical)",
        examples=["moderate"],
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Weighted-average confidence across all findings",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Actionable clinical recommendations",
    )
    disclaimer: str = Field(
        default=_DISCLAIMER,
        description="Legal / ethical disclaimer attached to every report",
    )

    model_config = {"from_attributes": True}
